version: '3.7'
services:
    db:
        image: tomaskubat/mariadb:10.5-dev-focal
        container_name: sandbox_phpnette_db
        ports:
            - 3391:3306
        volumes:
            - ./migrations:/docker-entrypoint-initdb.d:cached
        environment:
            ENV: development
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: project
            MYSQL_USER: project
            MYSQL_PASSWORD: project

    nginx:
        image: tomaskubat/nginx:1.19-dev-alpine
        container_name: sandbox_phpnette_nginx
        ports:
            - 8091:80
        volumes:
            - "${PWD}:/src:cached"
        environment:
            ENV: development

    php:
        image: tomaskubat/php:8.0-dev-fmp-alpine
        container_name: sandbox_phpnette_php
        volumes:
            - "${PWD}:/src:cached"
        environment:
            ENV: development
